include: package:flutter_lints/flutter.yaml
analyzer:  
  errors:
    avoid_unnecessary_containers: ignore
    prefer_const_constructors: ignore
    unnecessary_getters_setters: ignore
    avoid_print: ignore
    use_key_in_widget_constructors: ignore
    depend_on_referenced_packages: ignore 
    body_might_complete_normally_nullable: ignore
    constant_identifier_names: ignore
    prefer_final_fields: ignore
    non_constant_identifier_names: ignore 
    unused_field: ignore
    unnecessary_const: ignore
    unnecessary_new: ignore
    use_super_parameters: ignore
    unnecessary_import: ignore
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_literals_to_create_immutables: ignore